In [24]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import  KNeighborsClassifier
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

Email spam

In [2]:
df=pd.read_csv('email_spam.csv')
df.columns

Index(['word_free', 'word_offer', 'word_click', 'num_links', 'num_caps',
       'sender_reputation', 'is_spam'],
      dtype='object')

In [36]:
df.isnull().sum()

size_m2               0
distance_center_km    0
rating                0
num_reviews           0
price                 0
dtype: int64

In [39]:
df.isna().sum()

size_m2               0
distance_center_km    0
rating                0
num_reviews           0
price                 0
dtype: int64

In [7]:
X=df.drop(columns='is_spam')
y=df['is_spam']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
logreg=LogisticRegression()
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)
y_prob = logreg.predict_proba(x_test)[:, 1]   # Probabilities for ROC-AUC
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.3
Precision: 0.18181818181818182
Recall: 0.09523809523809523
F1 Score: 0.125
ROC-AUC: 0.2055137844611529
Confusion Matrix:
 [[10  9]
 [19  2]]


Customer churn or not

In [8]:
df=pd.read_csv('customer_churn.csv')
df.columns

Index(['tenure_months', 'monthly_charges', 'support_tickets', 'is_premium',
       'avg_usage_hours', 'churn'],
      dtype='object')

In [40]:
df.isnull().sum()

size_m2               0
distance_center_km    0
rating                0
num_reviews           0
price                 0
dtype: int64

In [41]:
df.isna().sum()

size_m2               0
distance_center_km    0
rating                0
num_reviews           0
price                 0
dtype: int64

In [11]:
x=df.drop(columns='churn')
y=df['churn']
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
logreg=LogisticRegression()
logreg.fit(x_train,y_train)
y_pred=logreg.predict(x_test)
y_prob=logreg.predict_proba(x_test)[:,1]
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.6
Precision: 0.6521739130434783
Recall: 0.6521739130434783
F1 Score: 0.6521739130434783
ROC-AUC: 0.6445012787723785
Confusion Matrix:
 [[ 9  8]
 [ 8 15]]


Disease stage

In [12]:
df=pd.read_csv('disease_stage.csv')
df.columns

Index(['age', 'b1', 'b2', 'b3', 'b4', 'stage'], dtype='object')

In [42]:
df.isnull().sum()

size_m2               0
distance_center_km    0
rating                0
num_reviews           0
price                 0
dtype: int64

In [43]:
df.isna().sum()

size_m2               0
distance_center_km    0
rating                0
num_reviews           0
price                 0
dtype: int64

In [23]:
x=df.drop(columns='stage')
y=df['stage']
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
logreg=LogisticRegression()
logreg.fit(x_train,y_train)
y_pred=logreg.predict(x_test)
y_prob=logreg.predict_proba(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred,average='macro'))
print("Recall:", recall_score(y_test, y_pred,average='macro'))
print("F1 Score:", f1_score(y_test, y_pred,average='macro'))
print("ROC-AUC:", roc_auc_score(y_test, y_prob,multi_class='ovr'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.275
Precision: 0.2577214452214452
Recall: 0.25772144522144524
F1 Score: 0.2569444444444444
ROC-AUC: 0.3662486240611241
Confusion Matrix:
 [[7 6 3]
 [3 2 6]
 [6 5 2]]


c:\Users\boomi\anaconda3\envs\pyai\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Flowers — k-NN Classification with CV

In [25]:
df=pd.read_csv('flowers.csv')
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [46]:
print("Missing values check:\n",df.isnull().sum())
print("Nan values check:\n",df.isna().sum())


Missing values check:
 size_m2               0
distance_center_km    0
rating                0
num_reviews           0
price                 0
dtype: int64
Nan values check:
 size_m2               0
distance_center_km    0
rating                0
num_reviews           0
price                 0
dtype: int64


In [27]:
x=df.drop(columns='species')
y=df['species']
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
#kNN with cv=5
param_grid={"n_neighbors": range(1, 26)}
knn = KNeighborsClassifier()
grid = GridSearchCV(knn, param_grid, cv=5)
grid.fit(X_train, y_train)
best_k = grid.best_params_["n_neighbors"]
best_knn = grid.best_estimator_
y_pred = best_knn.predict(X_test)
print("Best k:", best_k)
print("CV Score:", grid.best_score_)
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Best k: 22
CV Score: 0.43125
Test Accuracy: 0.225
Confusion Matrix:
 [[2 7 9]
 [5 3 4]
 [4 2 4]]


 Airbnb Prices — k-NN Regression with CV

In [32]:
from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
import numpy as np

In [29]:
df=pd.read_csv('airbnb.csv')
df.columns

Index(['size_m2', 'distance_center_km', 'rating', 'num_reviews', 'price'], dtype='object')

In [47]:
print("Missing values check:\n",df.isnull().sum())
print("Nan values check:\n",df.isna().sum())

Missing values check:
 size_m2               0
distance_center_km    0
rating                0
num_reviews           0
price                 0
dtype: int64
Nan values check:
 size_m2               0
distance_center_km    0
rating                0
num_reviews           0
price                 0
dtype: int64


In [35]:
x=df.drop(columns='price')
y=df['price']
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
param_grid={"n_neighbors":range(1,26)}
knn = KNeighborsRegressor()
grid = GridSearchCV(knn, param_grid, cv=5, scoring="neg_mean_squared_error")
grid.fit(x_train, y_train)
best_k = grid.best_params_["n_neighbors"]
best_knn = grid.best_estimator_
y_pred = best_knn.predict(x_test)
rmse = root_mean_squared_error(y_test, y_pred)
print("Best k:", best_k)
print("CV RMSE:", np.sqrt(-grid.best_score_))
print("Test RMSE:", rmse)
print("Test R²:", r2_score(y_test, y_pred))


Best k: 19
CV RMSE: 137.50411435034064
Test RMSE: 118.45506604724406
Test R²: -0.27334174969634817
